### ISSUE TITLE
unable to established connection

### ISSUE THREAD

**Issue by PapaSmurff415** [htrgouvea/nipe#121]
still it can't established a connection after starting it..i'm on kali linux 2020.1

**Comment by GouveaHeitor** [comment]
Hi @PapaSmurff415, 

I run some tests on Kali Linux 2020.1 and everything works correctly, could you give me more details about your error?

During the installation of Perl libraries, did everything go correctly?

If the bug is no longer persisting, please let me know.

**Comment by htrgouvea** [comment]
I will close this issue for lack of interaction ... Any news let me know!
