### ISSUE TITLE
Unable to run Nipe on root

### ISSUE THREAD

**Issue by stefins** [htrgouvea/nipe#124]
Hey,
When I'm trying to run
```sudo perl nipe.pl install```

[!] ERROR: this command could not be run

Running on MacOS
Thank you :)

**Comment by htrgouvea** [comment]
Hi,
Can you show me how you are executing the command?
Thx

**Comment by iamstefin** [comment]
`sudo perl niple.pl install`

**Comment by psyl0c** [comment]
I have the same problem on kali 2020.4.. 
something is fishy...

perl nipe.pl start
Nipe must be run as root.
----
sudo perl nipe.pl start (runs)
sudo perl nipe.pl status 
sometimes it connects , but mostly not, and I get this error:
[!] ERROR: sorry, it was not possible to establish a connection to the server.

if I run sudo perl nipe.pl restart
it connects and I get an ip

dont really get it ...


if I run sudo perl nipe.pl stop
sudo perl nipe.pl

**Comment by iamstefin** [comment]
even for `sudo perl nipe.pl start` I'm getting the same output

[!] ERROR: this command could not be run

**Comment by psyl0c** [comment]
have you tried run "sudo perl nipe.pl restart" not start
then check if your connected with "sudo perl nipe.pl status"

**Comment by iamstefin** [comment]
- Command `sudo perl nipe.pl restart` returns
   [!] ERROR: this command could not be run

- Command `sudo perl nipe.pl status` returns 
   [!] ERROR: sorry, it was not possible to establish a connection to the server.

**Comment by htrgouvea** [comment]
Hi @iamstefin, I will check the reason for these errors. This is very strange

**Comment by Mrpotato4** [comment]
Hi, it's happening also to me. Currently I'm running Nine on an Apple Silicon Mac, @iamstefin what is your Mac? This could be an Apple Silicon issue.
I tried to run Nipe through Rosetta 2 but nothing changes, every command I try (except from `sudo perl nipe.pl status`) it doesn't work and the terminal returns `[!] ERROR: this command could not be run`.
Also works `perl nipe.pl` for help. It's a very strange behavior, please help!

**Comment by kakumanivrn** [comment]
@htrgouvea Same issue for me as well. I am using macOS Catalina.

I tried running with both `sudo` and direct `root` account as well.

**Comment by marco-ulge** [comment]
I took a quick look, in `/lib/Nipe/Utils/Device.pm`,  the os config is determined based on `/etc/os-release` which is specific for Linux. I see also that later on it relies on iptables, which is also not available on OS X.

@htrgouvea let me know if you can use some help here

**Comment by MachineGunNFGC** [comment]
./nipe.pl start
Nipe must be run as root.

M also facing the same problem
Please help me to fix it
OS- termux

**Comment by htrgouvea** [comment]
Hi folks,

I just published a new version of Nipe, can you test it and tell me if it works now?

If it doesn't work, can you give me more information? Like the distribution they are using or any other information they find pertinent?

Thanks!

**Comment by kazani-351** [comment]
When I'm trying to run
sudo perl nipe.pl install

[!] ERROR: this command could not be run

Running on MacOS @htrgouvea

**Comment by Rod2012** [comment]
I got that error, I was running nipe on Kali in a VM (qemu) and **NetworkManager** didn't allow changes, so, I followed this: [https://askubuntu.com/questions/826177/networkmanager-permissions-error-on-xenial](https://askubuntu.com/questions/826177/networkmanager-permissions-error-on-xenial) and it worked as expected

**Comment by htrgouvea** [comment]
I'm closing this issue because Nipe doesn't work on MacOS due to the absence of iptables. If you are having problems with Nipe on a Linux distribution, you are welcome to comment or open new issues.
