### ISSUE TITLE
Mac OS installation

### ISSUE THREAD

**Issue by finjoetri** [htrgouvea/nipe#127]
Is it possible to install this in Mac?

**Comment by htrgouvea** [comment]
Hi @finjoetri,
Nipe works mainly around IpTables, and currently we don't have iptables available for MacOS.

**Comment by htrgouvea** [comment]
However, you can install Nipe on a VPS and connect to that VPS using an open source VPN service or something equivalent. It is a solution.


I'm thinking of ways to make Nipe available for Windows, Mac, Android and iOS devices in the future.
