### ISSUE TITLE
Sometimes works!

### ISSUE THREAD

**Issue by RichardBarron27** [htrgouvea/nipe#128]
**Is your feature request related to a problem? Please describe.**
This sometimes works and sometimes does not. It takes a while for it to work sometimes

**Describe the solution you'd like**Anyone know what the problem may be?

**Describe alternatives you've considered**

**Additional context**

**Comment by htrgouvea** [comment]
Hi @RichardBarron27,
Can you give me more information about this case? What is its distribution? is an error displayed?

**Comment by RichardBarron27** [comment]
The distribution is Kali 2020.4 and the error is    [!] ERROR: sorry, it was not possible to establish a connection to the server.

It does work eventually but takes a lot of tries.

**Comment by RichardBarron27** [comment]
I dont know if this helps but I have discovered that if all browsers are closed then start nipe it works ok.. It fails to work if browsers are open.

**Comment by htrgouvea** [comment]
I just published a new version of Nipe, can you test it and tell me if it works now?

If it doesn't work, can you give me more information? Like the distribution they are using or any other information they find pertinent?

Thanks!

**Comment by htrgouvea** [comment]
Hey @RichardBarron27,
Recently the Nipe has had many updates. Resolve some bugs that we managed to identify. Can we test again?
Thanks.

**Comment by htrgouvea** [comment]
Due to the lack of responses, I am closing this issue.
