### ISSUE TITLE
ERROR: sorry, it was not possible to establish a connection to the server

### ISSUE THREAD

**Issue by shom13** [htrgouvea/nipe#129]
Fresh install, followed instructions to download. After completion when checking status, this is what i am getting: ERROR: sorry, it was not possible to establish a connection to the server.

Found a couple other posts with the same issue but found no relevant solutions, hence creating a new issue.

**Comment by dakata1337** [comment]
Same here.

**Comment by shom13** [comment]
A simple reboot and a couple of tries did it for me. Sorry i forgot to post an update. Sometimes it wont connect at the first attempt. Try a few times with nipe start command, and it connects just fine.

**Comment by m7amad-nem** [comment]
it doesnt work :(

**Comment by shom13** [comment]
I have been using for a while, and it seems sometimes it wont connect the first time. The only way i can get it to work is by stop command. sudo perl nipe.pl stop followed by a start command sudo perl nipe.pl start. Repeat it for a few times and it should work.

**Comment by m7amad-nem** [comment]
> I have been using for a while, and it seems sometimes it wont connect the first time. The only way i can get it to work is by stop command. sudo perl nipe.pl stop followed by a start command sudo perl nipe.pl start. Repeat it for a few times and it should work. 

I wrote this code 
sudo perl nipe.pl stop && sudo perl nipe.pl start

but it still gives the same error. 
How many times should i repeat it?

**Comment by shom13** [comment]
Try a couple of times and it should connect. Check with status. I normally try separately, stop and then start without &&

**Comment by iis2h** [comment]
Commands after reboot : ( in nipe directory )
sudo perl nipe.pl stop
sudo perl nipe.pl start

it will work fine

**Comment by brokera** [comment]
through which ports does nipe work?

**Comment by shom13** [comment]
Check if your tor services are installed/running properly. If you're on linux open terminal and code in:
"curl --socks5 localhost:9050 --socks5-hostname localhost:9050 -s https://check.torproject.org/ | cat | grep -m 1 Congratulations | xargs"

If you get an output: Congratulations. This browser is configured to use Tor, try to start nipe again in nipe directory and it should work, else you need to setup tor properly as something could be wrong. Check /etc/tor/torrc directory

**Comment by brokera** [comment]
> Check /etc/tor/torrc directory

the connection error was not corrected. how to set up the tor correctly?

**Comment by brokera** [comment]
> If you get an output: Congratulations. This browser is configured to use Tor, try to start nipe again in nipe directory and it should work, else you need to setup tor properly as something could be wrong. Check /etc/tor/torrc directory

I was able to run nipe after completely removing the tor along with all the settings and folders and then installing it again (sudo apt install tor)
