### ISSUE TITLE
archlinux not working / double starting of tor

### ISSUE THREAD

**Issue by simkoc** [htrgouvea/nipe#134]
I am trying to run your script on arch. However, it fails and just bricks my internet.

During debugging I found that in `Start.pm` there are the lines
```
system ("tor -f .configs/$device{distribution}-torrc > /dev/null");
system ($startTor);
```

The first line already starts tor (as no --verify-config) is specified. Consequently, the second line fails as the required port is already in use (by the previously started tor).

However, even commenting out one of the lines does not make it work under arch.

**Comment by htrgouvea** [comment]
Hey @simkoc,
Recently the Nipe has had many updates. Resolve some bugs that we managed to identify. Can we test again?
Thanks.

**Comment by simkoc** [comment]
Thank you for updating your software, but I am afraid I have moved on to another solution and won't be able to test the bug fix.
