### ISSUE TITLE
can we have it on OpenSuse? :)

### ISSUE THREAD

**Issue by initdude** [htrgouvea/nipe#148]
i just wanna know that how we could have it on opensuse ??
many regards!
\m/

**Comment by andersonbosa** [comment]
For your knowledge guys, I tried to implement support to OpenSUSE but had some problems with cpanm dependencies. @initdude if you can lead it, here is an example PR of the changes:
  - https://github.com/htrgouvea/nipe/pull/149#issuecomment-1670419970

**Comment by htrgouvea** [comment]
Hey @initdude and @andersonbosa, we received a PR from @scriptprivate #162 to resolve this issues. Can you try Nipe again in OpenSUSE please? Thanks!
